### ISSUE TITLE
Update travis config to use xenial (Ubuntu 16.04)

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard#134]
Our readme says Ubuntu 16 is required, but our Travis testing uses 14. Hmm.

**Comment by ggggggggg** [comment]
I think it's really dastard commander that requires Ubuntu 16... its like python2.7 qt5 is hard to get on ubuntu 14.

**Comment by joefowler** [comment]
Ah! Right. But in that event, we should at least configure Travis to test on Xenial instead of Trusty (16 instead of 14). I vaguely remember that there's a problem with loading the required packages that we never figured out on 16. I will explore. If I can't make it work, I'll put this on hold.

According to [Travis documentation](https://docs.travis-ci.com/user/reference/overview/), they support only Ubuntu 12, 14, 16, and 14 is still the default. That means that 18 isn't a choice yet.
