### ISSUE TITLE
Lancero with testing

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard#14]
I'm making good progress at getting the lancero driver and dastard to talk to one another. The system works, as far as I can tell. However, there's a lot of code that is now untested. Make sure that the `lancero` package AND the `lancero_source.go` file both get extensive tests before we declare complete success.

**Comment by joefowler** [comment]
#19 covers the `LanceroSource` object to talk to the driver. But I still haven't figured out how to test it! Not even provisionally, i.e. on a system that has an available card. It should be possible, though.

**Comment by joefowler** [comment]
See #26. This is an attempt to test Lancero sources by providing an interface and a no-hardware implementation.

**Comment by ggggggggg** [comment]
fixed by #26
