### ISSUE TITLE
Dastard writes error files when I expect it not to

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#152]
Using the Lancero source with the experimental trigger, dastard appears to be writing error files and no group triggering. I expect it not to because I thought I made the experimental trigger mode turn off all triggering on error channels.

**Comment by joefowler** [comment]
When, exactly, do you expect it not to? What does that mean? What data source were you using?

**Comment by ggggggggg** [comment]
edited the first comment with more info

**Comment by ggggggggg** [comment]
This might be a dastard commander problem.

**Comment by ggggggggg** [comment]
I think this was a dastard commander problem.
