### ISSUE TITLE
Dastard shouldn't crash on missing data

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#163]
Currently, if dastard notices missing data (eg the frame bits are misaligned in lancero data), it panics. We should try hard to avoid this case, but we shouldn't panic. Instead we should use the CPU clock to estimate how much data is missing, update the framecount accordingly, and note the missing data in a file.

Ideally this would be implemented in a way that works for any data source so it doesn't need to be reimplemented over and over.

**Comment by joefowler** [comment]
Fixed by #166
