### ISSUE TITLE
zmq: consider using pure-Go implementation of ZeroMQ?

### ISSUE THREAD

**Issue by sbinet** [usnistgov/dastard#185]
hi there,

I stumbled on your repo via gonum.
I was wondering whether you considered using the pure-Go implementation of ZeroMQ: [go-zeromq/zmq4](https://github.com/go-zeromq/zmq4)? (it's being used in the Jupyter kernel for Go: [gophernotes](https://github.com/gopherdata/gophernotes)).

it would simplify the installation instructions.

**Comment by ggggggggg** [comment]
Thanks for the tip. I doubt we'll have time for this soon, but I'll leave the issue open in case someone has time in the future.
