### ISSUE TITLE
CURRENTIME message empty sometimes

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#194]
dcom is printing this out fairly regularly: `Error processing status message [topic,msg]: CURRENTTIME, 
`

Which I think means the `msg` component of CURRENTIME is empty.

**Comment by joefowler** [comment]
I don't really see how this can happen. Perhaps when that message is saved to `~/.dastard/config.yaml` and then read back, the `viper` library can't interpret it correctly as a time?

**Comment by joefowler** [comment]
Ah. The problem is that the message payload needs to be a valid JSON string, so enclosed in double-quotes if it contains spaces.
