### ISSUE TITLE
MaxSamples not being written correctly to off file headers

### ISSUE THREAD

**Issue by PSzypryt** [usnistgov/dastard#197]
Here's an example from some December RAVEN data.

`In [4]: ds.offFile.header
Out[4]:
{'ChannelIndex': 1,
 'ChannelName': 'chan1',
 'ChannelNumberMatchingName': 1,
 'MaxPresamples': 40,
 'MaxSamples': 0,
 'FramePeriodSeconds': 6.72e-06,
 'FileFormat': 'OFF',
 'FileFormatVersion': '0.2.0',
 'NumberOfBases': 3,
 'ModelInfo': {'Projectors': {'Rows': 3,
   'Cols': 80,
   'SavedAs': 'float64 binary data after header and before records. projectors first then basis, nbytes = rows*cols*8 for each projectors and basis'},
  'Basis': {'Rows': 80,
   'Cols': 3,
   'SavedAs': 'float64 binary data after header and before records. projectors first then basis, nbytes = rows*cols*8 for each projectors and basis'},
  'Description': ''},
 'CreationInfo': {'DastardVersion': '0.2.5',
  'GitHash': 'githash not computed',
  'SourceName': 'Lancero',
  'CreationTime': '2019-12-19T14:03:22.976732681-07:00'},
 'ReadoutInfo': {'NumberOfRows': 28,
  'NumberOfColumns': 8,
  'NumberOfChans': 448,
  'ColumnNum': 0,
  'RowNum': 0},
 'PixelInfo': {'XPosition': 0, 'YPosition': 0, 'Name': ''}}`

**Comment by ggggggggg** [comment]
https://github.com/usnistgov/dastard/blob/c86f1a51deba5406a16d20a15e0067e36aeb9e91/publish_data.go#L60

May have to do with that line, or something earlier.
