### ISSUE TITLE
AbacoSource needs to fill in data where packets are dropped

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard#202]
Firmware team insists that dropping of packets is theoretically possible and should be handled. Proposal at the moment is to replace missing packets with packets containing constant data.

**Comment by joefowler** [comment]
Need to check for packets dropped _between_ `AbacoSource.readerMainLoop` iterations, not just those lost from the packets returned by a single iteration. So far (in commit 5255eaf), we are only checking within one loop iteration.

**Comment by ggggggggg** [comment]
we need to also keep a log of datadrops
so in principle you can look back and identify that you cant trust the count rate at that time
