### ISSUE TITLE
Make the phase reset length a settable parameter

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#228]
It is hardcoded here: https://github.com/usnistgov/dastard/blob/e6bce83bff64b42a4b0f820744401fb97623a360/phase_unwrap.go#L29

**Comment by joefowler** [comment]
Proposal: 
1. In the expert tab of Dcom, we have a multiplier, say 5. This means `u.resetAfter` will be 5 record lengths.
2. Whenever user changes record length, the `u.resetAfter` number resets to 5 (or whatever) times the record length.

**Comment by ggggggggg** [comment]
What if you set the multiplier, so `u.resetAfter = round2int(float(recordLength)*multiplier)`. Then there is no magic, its just a bit more painful to get a certain value.
