### ISSUE TITLE
Fix the data rate indicator so that "filled in" packets don't count

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard#229]
Right now, when Abaco packets are missed, the `AbacoSource` fills in packets using `Packet.MakePretendPacket`. Unfortunately, these pretend packets are being counted in the data rate computation. This is pretty misleading when one is trying to understand that data were dropped.

Honestly, I like to know the rate of data that Dastard is actually processing (the number including pretend), but I can see that this is less relevant than the true Abaco-to-Dastard rate. And anyway, during normal times without data being dropped, the two rates are the same.

Proposal: dastard counts data in MB both with and without the artificial packets, sends both. DCom can print the current message when both are equal, and if they are unequal, it should print "1.342 MB/sec (15.342 MB/sec expected)" perhaps in Red.

**Comment by ggggggggg** [comment]
Seems good.
