### ISSUE TITLE
Can't use latest goczmq package: a deprecated API has been removed

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard#230]
See [goczmq release notes for 4.2.0](https://github.com/zeromq/goczmq/releases). Can we make compatible with the new API?

**Comment by ggggggggg** [comment]
It looks like it should be easy to become compatible, it's just a different way of setting socket options. Do we need to do this to make dastard installs work without fuss? Or can we just put an upper limit on the goczmq version we depend on?

**Comment by joefowler** [comment]
It was a 1-line fix, in the end. I'm updating all package dependencies. Will make a PR soon....
