### ISSUE TITLE
should we deploy binaries somehow?

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#236]
I ask because we want to make an integration test that includes dastard for scan_server. I'd rather not build from source, or just include the binary in that repo. So it would be nice if dastard binaries were available somewhere we could download them from for our test.

Example of how: https://blog.questionable.services/article/build-go-binaries-travis-ci-github/

**Comment by joefowler** [comment]
Hey, that is a great idea. That blog post is really slick. We should totally do it that way.
