### ISSUE TITLE
failed to close experimentStatefile with Abaco

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#239]
With the abaco source, if you use dcom to first start writing a file, then hit "stop writing", you get an RPC error originating from line 99 below and it appears to not actually stop writing.

https://github.com/usnistgov/dastard/blob/cc2d26404fd473b34123297ad9be3b68771b30aa/writing_state.go#L80-L103

The error it gives is "invalid argument" which may come from here: https://golang.org/src/os/file_posix.go?s=590:618#L11 which is odd because that seems to happen when the file is nil, which we just checked it is not?

**Comment by ggggggggg** [comment]
@danbek

**Comment by ggggggggg** [comment]
![Uploading A0E51AAB-21DB-441A-88FE-43C806EEEFCF.jpeg…]()

**Comment by ggggggggg** [comment]
![image](https://user-images.githubusercontent.com/5192577/114058938-1eb6c700-9851-11eb-90c5-51d0ab0d959f.png)

**Comment by joefowler** [comment]
Yeah, that's pretty strange. If we already verified that `ws.externalTriggerFile != nil` then maybe we should add to that line 99 error message. We should print out `ws.externalTriggerFile`. Maybe it's an invalid file handle? Maybe we opened that file and failed to panic or recover from an error back at file-opening time?

Is this project actually using external triggers? Or is this an error that arises when we aren't trying to use them?

Who's running this, and where?

**Comment by ggggggggg** [comment]
This is dan becker with abaco on 687medusa. It definitely does not have external triggers.

**Comment by ggggggggg** [comment]
I added some debug printing, and then I couldn't reproduce the problem. I then removed the debug printing, recompiled, and cannot reproduce the problem. Maybe they were running an older version?

**Comment by ggggggggg** [comment]
@danbek can still cause this
