### ISSUE TITLE
Group triggering cannot be enabled

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard#247]
This is a feature we never completed. Although there's a `TriggerBroker` in [group_trigger.go](https://github.com/usnistgov/dastard/blob/master/group_trigger.go), we don't have yet any RPC commands to activate its features. HEATES will need it.
* Add RPC commands to manipulate the trigger broker.
* Store configuration of group trigger.
* Make it work.
* Fix #235 (I assume this is related?)
* In Dastard-commander, make GUI elements that can do elementary group triggering.

**Comment by joefowler** [comment]
Also to do:

- [ ] Add some kind of crosstalk-like feature to BAHAMA so we can _test_ group triggering.

**Comment by ggggggggg** [comment]
fixed by #264

**Comment by joefowler** [comment]
This is absolutely _not_ fixed. All I did was to make FB->Error coupling work (in #264), which is a very specific special case.
