### ISSUE TITLE
missing config leads to sim pulse problems

### ISSUE THREAD

**Issue by danbek** [usnistgov/dastard#356]
This was dastard 0.3.4pre2 (git commit 4521992).

This is using the DR-TES flight computer.

If the `status:nsamples` config parameter in `.dastard/config.yaml` is 0 when you try to start the simulated pulse data source, dastard will start to allocate huge amount of memory (multiple GB).

This parameter defaults to 0 when you start dastard with a missing `config.yaml` file, which is what happens when a new dastard installation is first started.

After manually editing `config.yaml` and changing  `status:nsamples` to 500, and restarting dastard, the memory issue went away.

`status:npresamp` is also 0 in the default config, and I also changed it to a non-zero number, so it's possible that this is the problematic parameter, not `status:nsamples`

Note that I'm not using `dcom` for this - I'm using a script that I'm writing for Dr-TES. The script is attached. I'd run it like this:

`drtes.py sim 4 4`
[drcom.txt](https://github.com/user-attachments/files/16729970/drcom.txt)

**Comment by joefowler** [comment]
Do I understand correctly that you diagnose this problem _and_ #355 as resulting from the same cause: that record lengths default to 0? My idea to fix this and #355 is simply to default to 500 or 1000 samples in the absence of info from a config file.
