### ISSUE TITLE
test -race won't run with no_hardware

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard#42]
I don't understand this, but check out branch file_writing, which has a fix for #34, and try `go test -race`. It will fail like this:

```text
--- FAIL: TestNoHardwareSource (1.12s)
	lancero_test.go:116: reads were 865.100833ms apart, want < 500ms
```

Can you make sense of this? I don't want to dig into the no-hardware source.

**Comment by ggggggggg** [comment]
I can look a this, I know exactly what is going on, but I'm a bit surprised. It just means things are running a bit slower than expected.

**Comment by ggggggggg** [comment]
745203f should fix this, I pushed it to the file_writing branch, which maybe was not the best choice

**Comment by joefowler** [comment]
Why can't this test ever succeed during a race-check test? I don't get it.

But if you think this is the right way to go, then fine. Feel free to leave it only in branch file_writing. We'll merge that one soon.

**Comment by ggggggggg** [comment]
I don't have a good explanation, except that it seems like the -race flag makes this test really slow, to the point where it keeps falling farther behind. Maybe I could figure out a way to vastly reduce the datarate in the test? I guess I could try just turning lsync way up in the NoHardware source.

**Comment by ggggggggg** [comment]
Ok, I pushed a new way to fix it, which is just turning down the data rate, by turning up linePeriod.

Also the line period should be in the status bar in dastard-commander.

**Comment by joefowler** [comment]
Hmm, well this is a known problem: you need a lot of data to get an accurate LSYNC.

Perhaps we can replace a minimum number of samples with a minimum amount of time? I could go for that. Let's close this one and watch for whether LSYNC is computed correctly or not.
