### ISSUE TITLE
Trigger conditions for a newly started source are hard-coded, not restored from config

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastard#58]
The loop in `data_source.go`, specifically in `func (ds *AnySource) PrepareRun()` sets various "sensible defaults" for the trigger conditions when a new source is started.

If the trigger settings have been saved into a viper configuration file, *these* ought to override any defaults. Also, the defaults ought to be all triggers off.

**Comment by ggggggggg** [comment]
Agree! Probably the only default that should be non-zero is record length, maybe presamples.

**Comment by joefowler** [comment]
Possibly fixed in ddbded ?
