### ISSUE TITLE
publish number of records written to file

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#61]
This will allow `dastard-commander` to do two useful things
1. show the number of records written in the gui
2. have workflow wait for a certain number of records

It's a bit subtle because there could potentially be many types of records (LJH22, LJH3, OFF) being written.  Non-exhaustive options list:
1. publish a number for each file type
2. ensure all file types are in sync, publish one number
3. publish the largest number across all file types

**Comment by joefowler** [comment]
Closed with PR #62
