### ISSUE TITLE
Publish summary quantities only?

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#7]
Is it worth having a ZMQ socket (or topic within exising socket) that publishes the summary quantities (including model coefs) of a records, but leaves out the raw data?

**Comment by joefowler** [comment]
I don't see a strong argument for putting full records and summaries onto the same socket. But we certainly could, by clever use of topic filters in ZMQ. I lean to having a new socket just for summaries. (Be sure to update `PORTS.md` if you do this.)

**Comment by ggggggggg** [comment]
I did this, closing.
