### ISSUE TITLE
Dastard sends an empty message with topic CURRENTTIME

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#74]
Is this intended?

**Comment by joefowler** [comment]
I don't think so. I'll look into it. I think that was supposed to go in the settings _file_ only but not to be broadcast to clients.

**Comment by ggggggggg** [comment]
I don't see it anymore in #82, though I'm not sure where it was fixed.

**Comment by joefowler** [comment]
I kind of remember thinking that I fixed it, so I'm not surprised. I just couldn't find where, either.
