### ISSUE TITLE
Record length not restored correctly

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#78]
I think we still have the record length of a `DataStreamProcessor` hardcoded somewhere, so that when I set the record length short (say 400 samples, 66 presamples), then quit and restart dastard, the record length is actually 256 samples. Though dastard commander says the right value, so clearly we had access to it.

**Comment by ggggggggg** [comment]
I think the problem is related to this:
https://github.com/usnistgov/dastard/blob/45eb406206cc4b4694304f419fcce5a8dd0b4b2f/process_data.go#L74

**Comment by ggggggggg** [comment]
It seems like ConfigureSource should include a NSamples and NPresamples argument.

**Comment by joefowler** [comment]
Cannot reproduce with simulated pulses. Is this a Lancero-only thing?

Can you check your `~/.dastard/config.yaml` file after you quit dastard and before you restart it? Does it have the correct 400/66 value in its `status` object?

**Comment by joefowler** [comment]
Very weird! I do see the problem.
