### ISSUE TITLE
The heartbeat should include a unique ID, like the start time of dastard

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastard#79]
That way dastard command can tell if I quit dastard and restart it quickly.

**Comment by joefowler** [comment]
I guess we can do this. But what problem are you trying to solve? What would DC do with the information? Does it need to know that dastard has been restarted?

**Comment by ggggggggg** [comment]
The problem is that if I ctrl-C dastard, then quickly restart it, I think you can get into a state where it looks like things are working, but then dastard-commander crashes when you try to send a command.

**Comment by joefowler** [comment]
Actually, I'm going to send a NEWDASTARD message.
